### ISSUE TITLE
tarfile.ReadError: unexpected end of data

### ISSUE THREAD

**Issue by zingfeng** [Karthick47v2/quizzzy-backend#11]
Firstly, thank you so much for your repository 👏 
 
I tried to start docker but got this error. Could you suggest me a solution? 

```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env bash

# Let the DB start
sleep 10;
# Run migrations
alembic upgrade head

{"loglevel": "info", "workers": 1, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "0.0.0.0", "port": "80"}
{"loglevel": "info", "workers": 1, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "0.0.0.0", "port": "80"}
[2023-11-25 02:05:24 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-11-25 02:05:24 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2023-11-25 02:05:24 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-11-25 02:05:24 +0000] [8] [INFO] Booting worker with pid: 8
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Downloading: 100%|██████████| 1.18k/1.18k [00:00<00:00, 6.45MB/s]
Downloading: 100%|██████████| 190/190 [00:00<00:00, 1.46MB/s]
Downloading: 100%|██████████| 10.6k/10.6k [00:00<00:00, 42.4MB/s]
Downloading: 100%|██████████| 573/573 [00:00<00:00, 1.94MB/s]
Downloading: 100%|██████████| 116/116 [00:00<00:00, 930kB/s][2023-11-25 02:07:24 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2023-11-25 02:07:24 +0000] [1] [WARNING] Worker with pid 8 was terminated due to signal 6
[2023-11-25 02:07:24 +0000] [62] [INFO] Booting worker with pid: 62
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Downloading: 100%|██████████| 39.3k/39.3k [00:00<00:00, 164kB/s]
Downloading: 100%|██████████| 349/349 [00:00<00:00, 2.96MB/s]
Downloading: 100%|██████████| 134M/134M [00:11<00:00, 11.7MB/s] 
Downloading: 100%|██████████| 53.0/53.0 [00:00<00:00, 409kB/s]
Downloading: 100%|██████████| 112/112 [00:00<00:00, 642kB/s]
Downloading: 100%|██████████| 466k/466k [00:00<00:00, 1.82MB/s]
Downloading: 100%|██████████| 352/352 [00:00<00:00, 1.96MB/s]
Downloading: 100%|██████████| 13.2k/13.2k [00:00<00:00, 25.3MB/s]
Downloading: 100%|██████████| 232k/232k [00:00<00:00, 300kB/s] 
[2023-11-25 02:08:15 +0000] [62] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/main.py", line 26, in <module>
    false_ans_gen = FalseAnswerGenerator()
  File "/app/src/ansgenerator/false_answer_generator.py", line 26, in __init__
    self.__init_sense2vec()
  File "/app/src/ansgenerator/false_answer_generator.py", line 65, in __init_sense2vec
    safe_extract(file)
  File "/app/src/ansgenerator/false_answer_generator.py", line 57, in safe_extract
    for member in tar.getmembers():
  File "/usr/local/lib/python3.8/tarfile.py", line 1971, in getmembers
    self._load()        # all members, we first have to
{"loglevel": "info", "workers": 1, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": 1, "host": "0.0.0.0", "port": "80"}
  File "/usr/local/lib/python3.8/tarfile.py", line 2656, in _load
    tarinfo = self.next()
  File "/usr/local/lib/python3.8/tarfile.py", line 2572, in next
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
[2023-11-25 02:08:15 +0000] [62] [INFO] Worker exiting (pid: 62)
[2023-11-25 02:08:15 +0000] [1] [INFO] Shutting down: Master
[2023-11-25 02:08:15 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by Karthick47v2** [comment]
Hi @zingfeng , it seems s2v pretrained vectors aren't downloaded correctly. Have you tried again? maybe connection problems.

**Comment by ghost** [comment]
@Karthick47v2 Thank you for your reply but it still doesn't work
Can you update the [requirement.txt file ](https://github.com/Karthick47v2/quizzzy-backend/blob/main/app/requirements.txt)with the full version of the package. I think the reason is that the package version has not been fixed
```
fastt5==...
firebase-admin==...
keybert==...
keyphrase-vectorizers==...
sentence_transformers==...
sense2vec==...
gdown==...
```

**Comment by Karthick47v2** [comment]
@datbt-2563, I just ran it. Problem is, it tries to extracts tar file directly from online source rather than saving it first.  Thanks for pointing out, I have updated the code. Replace `__init_sense2vec()` function from [app/src/ansgenerator/false_answer_generator.py](https://github.com/Karthick47v2/quizzzy-backend/blob/9062c5150c5554155e19d3b0c91abd17d5771f54/app/src/ansgenerator/false_answer_generator.py#L36C4-L68) with below.

```
def __init_sense2vec(self):
        """Initialize word vectors to get similar words.

           https://github.com/explosion/sense2vec
        """

        if not os.path.isdir(os.getcwd() + '/s2v_old'):
            s2v_url = "https://github.com/explosion/sense2vec/releases/download/"
            s2v_ver_url = s2v_url + "v1.0.0/s2v_reddit_2015_md.tar.gz"

            with urllib.request.urlopen(s2v_ver_url) as req:
                # save downloaded to a temp file first
                with tempfile.NamedTemporaryFile(delete=False) as temp_file:
                    temp_file.write(req.read())
                    temp_file_path = temp_file.name

            with tarfile.open(temp_file_path, mode='r:gz') as file:
                def is_within_directory(directory, target):
                    abs_directory = os.path.abspath(directory)
                    abs_target = os.path.abspath(target)
                    prefix = os.path.commonprefix([abs_directory, abs_target])
                    return prefix == abs_directory

                def safe_extract(tar, path=".", members=None, *, numeric_owner=False):
                    for member in tar.getmembers():
                        member_path = os.path.join(path, member.name)
                        if not is_within_directory(path, member_path):
                            raise Exception("Attempted Path Traversal in Tar File")
                    tar.extractall(path, members, numeric_owner=numeric_owner)

                safe_extract(file)

        self._s2v = Sense2Vec().from_disk("s2v_old")
```

Thanks for the suggestion on `requirements.txt`, I only specified versions for packages which breaks the functionality, others should works fine if Python (3.8) version is same.

**Comment by zingfeng** [comment]
@Karthick47v2 It worked! ❤️ Thank you!
